title: "whaler"
author: whaler
email: alex@treebeard.io
description: >-
  whaler example
exclude_patterns:
  - .*/*
  - .*/**/*
  - _build
only_build_toc_files: true
html:
  use_edit_page_button: true
  use_repository_button: true

repository:
  url: https://github.com/treebeardtech/whaler
  branch: main
  path_to_book: docs

launch_buttons:
  thebe: false
  binder: false

execute:
  execute_notebooks: force