on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: ubuntu-latest
            python-version: "3.7"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.7"
            pytest-opts: "-m 'not docker'"
          - os: macos-latest
            python-version: "3.8"
            pytest-opts: "-m 'not docker'"
          - os: macos-latest
            python-version: "3.9"
            pytest-opts: "-m 'not docker'"

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.cfg.python-version }}
      - run: pip install poetry
      - run: poetry -V
      - run: poetry install
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --verbose --all-files

      - run: poetry run pytest ${{ matrix.cfg.pytest-opts }}
